# Tarea - Programación lineal

## Diseño de la Dieta Óptima

Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en $100$ gramos, se deben tener **por lo menos** $8$ gramos de proteína y $6$ gramos de grasa. Así mismo, no se debe tener más de $2$ gramos de fibra y $0.4$ gramos de sal.  

Los datos nutricionales se pueden obtener de la siguiente tabla:

Ingrediente|Proteína|Grasa|Fibra|Sal
:----|----|----|----|----
Pollo|  10.0%|08.0%|00.1%|00.2%
Carne|  20.0%|10.0%|00.5%|00.5%
Cordero|15.0%|11.0%|00.5%|00.7%
Arroz|  00.0%|01.0%|10.0%|00.2%
Trigo|  04.0%|01.0%|15.0%|00.8%
Gel|    00.0%|00.0%|00.0%|00.0%

Los costos de cada producto son:

Ingrediente|Costo por gramo
:----|----
Pollo|$\$$0.013
Carne|$\$$0.008
Cordero|$\$$0.010
Arroz|$\$$0.002
Trigo|$\$$0.005
Gel|$\$$0.001    

Lo que se busca optimizar en este caso es la cantidad de productos que se debe utilizar en la comida de gato, minimizando el costo total. Para simplificar la notación use las siguientes variables: 

+ $x_1:$ Gramos de pollo  
+ $x_2:$ Gramos de carne  
+ $x_3:$ Gramos de cordero  
+ $x_4:$ Gramos de arroz  
+ $x_5:$ Gramos de trigo  
+ $x_6:$ Gramos de gel

La tarea consiste en plantear el problemade programación lineal que permita satisfacer las necesidades alimenticias del gato al tiempo que minimice el costo total y resolverlo con `linprog`.

### Criterio de optimización

* Minimizar costos

### Función objetivo

$ min --> 0.013x_1 + 0.008x_2 + 0.010x_3 + 0.002x_4 + 0.005x_5 + 0.001x_6 $

### Restricciones

$ Proteína: 0.1x_1 + 0.2x_2 + 0.15x_3 + 0.04x_5 \geq 8 $

$ Grasa: 0.08x_1 + 0.1x_2+ 0.11x_3 + 0.01x_4 + 0.01x_5 \geq 6 $

$ Fibra: 0.001x_1 + 0.005x_2 + 0.005x_3 + 0.1x_4 +0.15x_5 \leq 2 $

$ Sal: 0.002x_1 + 0.005x_2 + 0.007x_3 + 0.002x_4 + 0.008x_5 + \leq 0.4 $

$ x_1 + x_2 + x_3 + x_4 + x_5 + x_6 = 100 $

In [1]:
import numpy as np
import scipy.optimize as opt

In [24]:
c = np.array([[0.013, 0.008, 0.010, 0.002, 0.005, 0.001]])
r = np.array([[-0.1, -0.2, -0.15, 0, -0.04, 0],
              [-0.08, -0.1, -0.11, -0.01, -0.01, 0],
              [0.001, 0.005, 0.005, 0.1, 0.15, 0],
              [0.002, 0.005, 0.007, 0.002, 0.008, 0],
              [-1, -1, -1, -1, -1, -1]])
l = np.array([[-8, -6, 2, 0.4, -100]])

respuesta = opt.linprog(c, r, l, method="simplex")
respuesta

     con: array([], dtype=float64)
     fun: 0.52
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([4. , 0. , 1.7, 0.1, 0. ])
  status: 0
 success: True
       x: array([ 0., 60.,  0.,  0.,  0., 40.])

In [25]:
respuesta.x

array([ 0., 60.,  0.,  0.,  0., 40.])

## Problema de distribución de energía eléctrica

La Comisión Federal de Electricidad **(CFE)** dispone de cuatro plantas de generación para satisfacer la demanda diaria eléctrica en cuatro ciudades, Guadalajara, León y Morelia. Las plantas $1$, $2$ y $3$ pueden satisfacer $80$, $40$ y $60$ millones de KW al día respectivamente. Las necesidades de las ciudades de Guadalajara, León y Morelia son de $70$, $40$ y $70$ millones de Kw al día respectivamente. 


Los costos asociados al envío de suministro energético por cada millón de Kw entre cada planta y cada ciudad son los registrados en la siguiente tabla. 

-|Guadalajara|León|Morelia
:----|----|----|----
Planta 1|5|2|7
Planta 2|3|6|6
Planta 3|6|1|2

Y por último, las restricciones del problema, van a estar dadas por las capacidades de oferta y demanda de cada planta (en millones de KW) y cada ciudad.

Para simplificar la notación use las siguientes variables:

+ $x_1$: Kw (en millones) distribuidos de la Planta 1 a Guadalajara
+ $x_2$: Kw (en millones) distribuidos de la Planta 1 a León
+ $x_3$: Kw (en millones) distribuidos de la Planta 1 a Morelia
+ $x_4$: Kw (en millones) distribuidos de la Planta 2 a Guadalajara
+ $x_5$: Kw (en millones) distribuidos de la Planta 2 a León
+ $x_6$: Kw (en millones) distribuidos de la Planta 2 a Morelia
+ $x_7$: Kw (en millones) distribuidos de la Planta 3 a Guadalajara
+ $x_8$: Kw (en millones) distribuidos de la Planta 3 a León
+ $x_9$: Kw (en millones) distribuidos de la Planta 3 a Morelia

La tarea consiste en plantear el problema de programación lineal que permita satisfacer las necesidades de todas las ciudades al tiempo que minimice los costos asociados a la distribución y resolverlo con `linprog`.

### Criterio de optimización

* Minimizar costos

### Función objetivo

$ min --> 5x_1 + 2x_2 + 7x_3 + 3x_4 + 6x_5 + 6x_6 + 6x_7 + x_8 + 2x_9 $

### Restricciones 

$ x_1 + x_2 + x_3 \leq 80 $

$ x_4 + x_5 + x_6 \leq 40 $

$ x_7 + x_8 + x_9 \leq 60 $

$ x_1 + x_4 + x_7 \geq 70 $

$ x_2 + x_5 + x_8 \geq 40 $

$ x_3 + x_6 + x_9 \geq 70 $

In [26]:
import numpy as np
import scipy.optimize as opt

In [29]:
c = np.array([[5, 2, 7, 3, 6, 6, 6, 1, 2]])
r = np.array([[1, 1, 1, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 1, 1, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 1, 1, 1],
              [-1, 0, 0, -1, 0, 0, -1, 0, 0],
              [0, -1, 0, 0, -1, 0, 0, -1, 0],
              [0, 0, -1, 0, 0, -1, 0, 0, -1]])
l = np.array([[80, 40, 60, -70, -40, -70]])

respuesta = opt.linprog(c, r, l, method="simplex")
respuesta

     con: array([], dtype=float64)
     fun: 540.0
 message: 'Optimization terminated successfully.'
     nit: 9
   slack: array([0., 0., 0., 0., 0., 0.])
  status: 0
 success: True
       x: array([30., 40., 10., 40.,  0.,  0.,  0.,  0., 60.])

In [30]:
respuesta.x

array([30., 40., 10., 40.,  0.,  0.,  0.,  0., 60.])

# Trabajos en clase para puntos extra :)

## Problema de transporte

### Criterio de optimización

* Minimizar costos

### Función objetivo

$ min --> 50A_C + 60A_D + 10A_E + 25B_C + 40B_D + 20B_E $

### Restricciones

$ A_C + B_C \geq 200 $

$ A_D + B_D \geq 300 $

$ A_E + B_E \geq 400 $

$ A_C + A_D + A_E \leq 500 $

$ B_C + B_D + B_E \leq 400 $

In [31]:
import numpy as np
import scipy.optimize as opt

In [32]:
g = np.array([[50, 60, 10, 25, 40, 20]])
r = np.array([[1, 1, 1, 0, 0, 0],
              [0, 0, 0, 1, 1, 1],
              [-1, 0, 0, -1, 0, 0],
              [0, -1, 0, 0, -1, 0],
              [0, 0, -1, 0, 0, -1]])
l = np.array([[500, 400, -200, -300, -400]])

respuesta = opt.linprog(g, r, l, method="simplex")
respuesta

     con: array([], dtype=float64)
     fun: 23000.0
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([0., 0., 0., 0., 0.])
  status: 0
 success: True
       x: array([  0., 100., 400., 200., 200.,   0.])

In [33]:
respuesta.x

array([  0., 100., 400., 200., 200.,   0.])

## Inversión en bonos

### Criterio de optimización

* Minimizar costos

### Función objetivo

$ max --> 0.0865A_1 + 0.095A_2 + 0.1A_3 + 0.0875A_4 + 0.0925A_5 + 0.09A_6 $

### Restricciones

$ A_1 + A_2 + A_3 + A_4 + A_5 + A_6 \leq 750,000 $

$ A_1 + A_2 + A_4 + A_6 \geq 375,000 $

$ A_2 + A_3 + A_5 \leq 262,500 $

$ A_1 \leq 187,500 $

$ A_2 \leq 187,500 $

$ A_3 \leq 187,500 $

$ A_4 \leq 187,500 $

$ A_5 \leq 187,500 $

$ A_6 \leq 187,500 $

In [ ]:
import numpy as np
import scipy.optimize as opt

In [34]:
g = np.array([[0.0865, 0.095, 0.1, 0.0875, 0.0925, 0.09]])
r = np.array([[1, 1, 1, 1, 1, 1],
              [-1, -1, 0, -1, 0, -1],
              [0, 1, 1, 0, 1, 0],
              [1, 0, 0, 0, 0, 0],
              [0, 1, 0, 0, 0, 0],
              [0, 0, 1, 0, 0, 0],
              [0, 0, 0, 1, 0, 0],
              [0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 1]])
l = np.array([750000, -375000, 262500, 187500, 187500, 187500, 187500, 187500, 187500])

respuesta = opt.linprog(g, r, l, method="simplex")
respuesta

     con: array([], dtype=float64)
     fun: 32625.0
 message: 'Optimization terminated successfully.'
     nit: 16
   slack: array([375000.,      0., 262500.,      0., 187500., 187500.,      0.,
       187500., 187500.])
  status: 0
 success: True
       x: array([187500.,      0.,      0., 187500.,      0.,      0.])

In [35]:
respuesta.x

array([187500.,      0.,      0., 187500.,      0.,      0.])